Hw1
VIXER13/AdvCpp-2020.1 pull request #1
Opened 2020-03-18 20:22 UTC by VIXER13

2020-03-18 20:47 UTC, smirnov-vs requested changes

2020-03-18 20:47 UTC, smirnov-vs commented on include/process.hpp
> +    std::array<int, 2> fd = {-1, -1};
лучше именовать переменные, разделить на два отдельных поля

2020-03-18 20:47 UTC, smirnov-vs commented on src/process.cpp
> +        if (dup2(fd[0], 0) < 0 || dup2(fd[1], 1) < 0) {
стоит использовать константы типа `STDIN_FILENO`

2020-03-18 20:47 UTC, smirnov-vs commented on src/process.cpp
> +        if (dup2(fd[0], 0) < 0 || dup2(fd[1], 1) < 0) {
что-то не так, дочерний процесс пишет сам себе на stdin?
надо разобраться и протестировать

2020-03-18 20:47 UTC, smirnov-vs commented on src/process.cpp
> +    return buff.st_blksize;
проверка конца данных из дескриптора проверяется через `read`

2020-03-18 20:47 UTC, smirnov-vs commented on src/process.cpp
> +    return ::read(fd[0], data, len);
системный read возвращает не size_t

2020-03-18 20:47 UTC, smirnov-vs commented on src/process.cpp
> +        if (read_out == -1) {
это логика метода read, который можно тут использовать

2020-03-18 20:47 UTC, smirnov-vs commented on src/simple_dialog.cpp
> +        std::cin >> str.data();
что если больше 256?

2020-03-18 20:47 UTC, smirnov-vs commented on src/simple_dialog.cpp
> +        proc.writeExact(str.data(), strlen(str.data()));
надо переделать str на подходящий контейнер

2020-03-18 20:47 UTC, smirnov-vs commented on CMakeLists.txt
> +add_executable(hw1 ${SOURCES})
где библиотека?)

2020-03-18 20:47 UTC, smirnov-vs commented on src/main.cpp
> +            if (!simpleDialog(proc))
надо отступы пофиксить

2020-03-18 20:47 UTC, smirnov-vs commented on src/main.cpp
> +        Process proc(argv[1]);
там исключения внутри

2020-03-18 20:54 UTC, a-badin reviewed
Правим второй пайп, выделяем библиотеку в отдельный  файл. Можно сделать свой echo процесс, чтобы на нем отлаживаться

2020-03-18 20:54 UTC, a-badin commented on CMakeLists.txt
> +set(SOURCES src/main.cpp src/process.cpp src/simple_dialog.cpp)
Предлагаю вынести process.hpp и process.cpp в отдельную библиотеку в папке lib

2020-03-18 20:54 UTC, a-badin commented on include/process.hpp
> +        return message.data();
у data может не оказаться 0 в конце строки. c_str() это гарантирует

2020-03-18 20:54 UTC, a-badin commented on include/process.hpp
> +
Если будет библиотека, желательно добавить пространство имен

2020-03-18 20:54 UTC, a-badin commented on include/process.hpp
> +#endif
Хорошим стилем считается добавлять комментарий какой ifdef закрывается

2020-03-18 20:54 UTC, a-badin commented on src/main.cpp
> +        std::cerr << "Argc < 2." << std::endl;
наверное, надо вернуть код отличный от 0

2020-03-18 20:54 UTC, a-badin commented on src/process.cpp
> +        if (execl(path.data(), path.data(), nullptr) < 0) {
c_str

2020-03-18 20:54 UTC, a-badin commented on src/process.cpp
> +    if (pipe(fd.data()) < 0) {
Одним пайпом тут не справится. С одним пайпом ваша программа работает до тех пор, пока ваш процесс повторяет то что принимает. Если, например, передать аргумент программу /bin/date, и передать ей строку 123, а потом считать 35 байт, то получим дату + 123. Но дочерний процесс не отправлял 123. Так получается потому, что и родитель и дочений процессы пишут и читают из одного пайпа.

2020-03-18 21:15 UTC, a-badin commented on include/process.hpp
> +        return message.data();
Тут я не прав, с 11 гарантируется

2020-03-18 21:31 UTC, VIXER13 commented on include/process.hpp
> +    std::array<int, 2> fd = {-1, -1};
То есть вместо массива использовать структуру, которую в случае необходимости представлять как массив? А не возникнет ли проблем с каким-нибудь выравниванием? Не лучше ли тогда создать внутри класса enum {IN, OUT}, и вместо индексов подставлять константы из него?

2020-03-18 21:31 UTC, VIXER13 commented on src/process.cpp
> +        if (dup2(fd[0], 0) < 0 || dup2(fd[1], 1) < 0) {
Про константу не знал, обязательно заменю, а про то кто куда пишет буду завтра разбираться.

2020-03-18 21:31 UTC, VIXER13 commented on src/process.cpp
> +    return ::read(fd[0], data, len);
Да, он возвращает ssize_t, то есть тип той же размерности, что и size_t, но со знаком. Но я не вижу здесь смысла в явной конвертации типа, потому что беззнаковый тип и так считается шире, чем знаковый, поэтому он совершенно легально сконвертируется в нужный нам size_t. Но только мне всё равно не очень нравится то, что в случае ошибки нам вернётся очень огромное число. С другой стороны можно вспомнить про std::string::npos, который в свою очередь и является size_t(-1), тогда моя реализация будет повторять это поведение.

Или я неправильно понял претензию?

2020-03-18 21:31 UTC, VIXER13 commented on src/simple_dialog.cpp
> +        std::cin >> str.data();
Ничего хорошего, заменю на std::string

2020-03-18 21:31 UTC, VIXER13 commented on src/simple_dialog.cpp
> +        proc.writeExact(str.data(), strlen(str.data()));
Заменю на std::string

2020-03-18 21:31 UTC, VIXER13 commented on src/main.cpp
> +            if (!simpleDialog(proc))
Действительно. Странно, что линтеры не ругались

2020-03-19 17:46 UTC, VIXER13 commented
Я так и не понял как при помощи read проверять isReadable. Я если пытаюсь читать из пустого пайпа, то у меня всё повисает и ждёт, пока он чем-то заполнится.

2020-03-20 11:37 UTC, smirnov-vs commented on include/process.hpp
> +    std::array<int, 2> fd = {-1, -1};
почему мы здесь боремся за выравнивание?)
выравнивание двух элементов в массиве не отличается от выравнивания двух последовательных полей структуры

конкретно с enum будет просто больше кода, не вижу особого смысла в этом, писать надо проще

2020-03-20 11:38 UTC, smirnov-vs commented on src/process.cpp
> +    return ::read(fd[0], data, len);
проблему нашел, а претензию не понял
нужно обработать исключительный случай с -1 и дальше конвертировать в `size_t`

2020-03-20 11:39 UTC, smirnov-vs commented
Читать не надо, если пайп уже кончился, просто по факту окончания пайпа запоминать это

2020-03-20 12:31 UTC, VIXER13 commented on include/process.hpp
> +    std::array<int, 2> fd = {-1, -1};
Прислушался к совету, завёл структуру.

2020-03-20 12:34 UTC, VIXER13 commented on src/process.cpp
> +    return ::read(fd[0], data, len);
Теперь, и read, и write кидают исключения. Хотя, как мне кажется, это немного лишнее, учитывая, что функции что-то, да возвращают и size_t(-1) можно обработать как ошибку, в отличие от Exact методов, где исключения оправданы.

2020-03-20 13:12 UTC, smirnov-vs commented on include/process.hpp
> +    std::array<int, 2> fd = {-1, -1};
зачем структура? говорили просто про 2 отдельных поля

2020-03-20 13:13 UTC, smirnov-vs commented on src/process.cpp
> +    return ::read(fd[0], data, len);
ошибки отдельно удобно обрабатывать, результаты отдельно

2020-03-20 13:37 UTC, VIXER13 commented on include/process.hpp
> +    std::array<int, 2> fd = {-1, -1};
Мне кажется такой вариант
```
struct {
    int read = -1, write = -1;
} fd_in, fd_out;
```
выглядит лучше, чем такой
`int read_in = -1, write_in = -1, read_in = -1, read_out = -1;`
Потому что он позволяет выделить особенность, что это две связанные переменные и с ними надо обращаться, как с единым объектом.

2020-03-20 13:40 UTC, smirnov-vs commented on include/process.hpp
> +    std::array<int, 2> fd = {-1, -1};
да, просто в конкретном случае классу достаточно знать всего 2 дескриптора, которые проще описать двумя переменными

2020-03-20 13:56 UTC, VIXER13 commented on include/process.hpp
> +    std::array<int, 2> fd = {-1, -1};
Аа, понял, нам же не нужны read_in и write_out. Но ток у меня при их закрытии почему-то программа падает при попытке писать, например, в /bin/date. И не выдаёт никаких ошибок, просто завершается. Конечно, я понимаю, что это бессмысленно, но не понимаю, должна ли она при этом падать и если не должна, то как ловить? С /bin/cat всё работает.

2020-03-20 14:07 UTC, smirnov-vs commented on include/process.hpp
> +    std::array<int, 2> fd = {-1, -1};
программа может упасть от сигнала, может упасть от исключения через `abort()`, скорее всего у тебя SIGPIPE, пишешь в закрытый пайп, добро пожаловать в дебаг

2020-03-20 17:22 UTC, VIXER13 commented on include/process.hpp
> +    std::array<int, 2> fd = {-1, -1};
Убрал лишние дескрипторы, нужно ли ловить SIGPIPE и как это вообще делать?

2020-03-23 20:29 UTC, smirnov-vs commented on include/process.hpp
> +    std::array<int, 2> fd = {-1, -1};
sigpipe можешь игнорировать приложением, которое использует бибилиотеку

2020-03-23 20:36 UTC, smirnov-vs requested changes

2020-03-23 20:36 UTC, smirnov-vs commented on lib/src/process.cpp
> +        readable = false;
это неверная проверка на EOF, гугл тут поможет

2020-03-23 20:36 UTC, smirnov-vs commented on lib/src/process.cpp
> +        closeAllPipes(fd_in, fd_out);
может лучше применить RAII?
мне например тут и ниже довольно сложно выследить всегда ли ты все закрыл при ошибке

2020-03-23 20:36 UTC, smirnov-vs commented on lib/src/process.cpp
> +        if (static_cast<char*>(data)[i] == '\0') {
терминальный нуль это не EOF для read

2020-03-23 20:36 UTC, smirnov-vs commented on CMakeLists.txt
> +add_executable(hw1 ${SOURCES} ${LIB_SOURCES})
нет библиотеки все еще тут

2020-03-24 19:21 UTC, VIXER13 commented on lib/src/process.cpp
> +        closeAllPipes(fd_in, fd_out);
Добавил класс Descriptor

2020-03-24 19:22 UTC, VIXER13 commented on CMakeLists.txt
> +add_executable(hw1 ${SOURCES} ${LIB_SOURCES})
Теперь есть :)

2020-03-24 19:23 UTC, VIXER13 commented on lib/src/process.cpp
> +        if (static_cast<char*>(data)[i] == '\0') {
Я просто не совсем правильно понял, что от меня в итоге требовалось. Я в итоге здесь не терминальный нуль поставил, а макрос EOF

2020-03-24 23:53 UTC, smirnov-vs commented on process_lib/src/process.cpp
> +    if (pipe(reinterpret_cast<int*>(fd_in.data())) < 0 || pipe(reinterpret_cast<int*>(fd_out.data())) < 0) {
лучше не хачить, а сделать просто класс пайпу

2020-03-24 23:53 UTC, smirnov-vs commented on lib/src/process.cpp
> +        if (static_cast<char*>(data)[i] == '\0') {
это все равно неверно, EOF это просто -1
что если я отправлю в пайп среди своих данных -1?

2020-03-24 23:54 UTC, smirnov-vs requested changes
еще остались проблемы

2020-03-25 21:18 UTC, smirnov-vs commented on process_lib/src/descriptor.cpp
> +    other.fd_ = -1;
а зачем выделять в отдельную функцию?

2020-03-25 21:18 UTC, smirnov-vs commented on process_lib/src/pipe.cpp
> +    fds_[0] = std::move(Descriptor(fds[0]));
это и так rvalue

2020-03-25 21:18 UTC, smirnov-vs commented on process_lib/src/pipe.cpp
> +    fds_[0] = std::move(other.fds_[0]);
мув инта

2020-03-25 21:18 UTC, smirnov-vs commented on process_lib/src/pipe.cpp
> +    return fds_[i];
тут скорее доступ через enum нужен, только 2 варианта

2020-03-25 21:18 UTC, smirnov-vs commented on process_lib/src/process.cpp
> +    ::close(write_in);
это класс, так что лучше вызывать его метод close, который уже делает всё

2020-03-25 21:25 UTC, VIXER13 commented on process_lib/src/descriptor.cpp
> +    other.fd_ = -1;
Чтобы не повторять код в конструкторе перемещения и в операторе присваивания с перемещением

2020-03-25 21:26 UTC, VIXER13 commented on process_lib/src/pipe.cpp
> +    fds_[0] = std::move(Descriptor(fds[0]));
Да, но если я убираю мув, то у меня компилятор ругается

2020-03-25 21:27 UTC, smirnov-vs commented on process_lib/src/descriptor.cpp
> +    other.fd_ = -1;
обычно это решают через copy-and-swap

2020-03-25 21:27 UTC, VIXER13 commented on process_lib/src/pipe.cpp
> +    fds_[0] = std::move(other.fds_[0]);
Это оправдано тем, что при муве у нас в other.fds_[0] внутренний int будет заменён на -1, чтобы дескриптор не закрылся при выходе из зоны видимости объекта.

2020-03-25 21:28 UTC, smirnov-vs commented on process_lib/src/pipe.cpp
> +    fds_[0] = std::move(Descriptor(fds[0]));
что пишет? все должно быть ок

2020-03-25 21:31 UTC, VIXER13 commented on process_lib/src/pipe.cpp
> +    fds_[0] = std::move(Descriptor(fds[0]));
Ошибся с местом использования std::move, тут действительно всё хорошо

2020-03-25 21:47 UTC, VIXER13 commented on process_lib/src/descriptor.cpp
> +    other.fd_ = -1;
Здесь, кстати, в другом даже ошибка была. Я не закрывал дескриптор other

2020-03-25 21:47 UTC, VIXER13 commented on process_lib/src/descriptor.cpp
> +    other.fd_ = -1;
В смысле, наоборот, не закрывал текущий дескриптор, прежде, чем его заменить

2020-03-28 13:31 UTC, smirnov-vs approved these changes

2020-03-28 13:31 UTC, merged