done
VIXER13/AdvCpp-2020.1 pull request #2
Opened 2020-03-25 13:43 UTC by VIXER13

2020-04-02 09:26 UTC, VIXER13 commented
ping

2020-04-04 11:10 UTC, a-badin requested changes

2020-04-04 11:10 UTC, a-badin commented on CMakeLists.txt
> +include_directories(${HEADERS})
Давайте пользоваться хорошими практиками, вашей библиотеке logger не нужны заголовки logger/include
сделайте target_include_directories. В принципе можно вынести на logger отдельный CMakeFile

2020-04-04 11:10 UTC, a-badin commented on log_lib/include/BaseLogger.hpp
> +    explicit BaseLogger(const Level lvl);
Зачем тут const

2020-04-04 11:10 UTC, a-badin commented on log_lib/include/BaseLogger.hpp
> +    inline static const std::array<std::string, 4> message_level = {"DEBUG: ", "INFO: ", "WARNING: ", "ERROR: "};
не очень безопасно и неудобно расширять, надо следить за размером.
Enum приходится кастить к size_t.
сделайте метод std::string get_prefix(Level level); тогда все константы попадут в реалзиацию класса тз его объявления. Заведите константу в реализации map<Level, std::string> тогда вы не  будете завязаны ни на тип enum, ни на кто из них 0, а кто 4

2020-04-04 11:10 UTC, a-badin commented on log_lib/include/FileLogger.hpp
> +    explicit FileLogger(const std::string& path, const Level lvl);
explicit не нужен если аргумента 2

2020-04-04 11:10 UTC, a-badin commented on log_lib/include/FileLogger.hpp
> +    std::ofstream fout;
дэш на приватный член класса

2020-04-04 11:10 UTC, a-badin commented on log_lib/include/BaseLogger.hpp
> +    std::string message;
дэш на приватнй член класса

2020-04-04 11:10 UTC, a-badin commented on log_lib/src/Logger.cpp
> +    Logger::get_instance().set_global_logger(std::make_unique<StdoutLogger>(lvl));
Имелось ввиду просто создать unique_ptr на логгер

2020-04-04 11:10 UTC, a-badin commented on log_lib/src/Logger.cpp
> +    std::unique_ptr<BaseLogger>& get_global_logger() noexcept {
Чем обоснован выбор `std::unique_ptr<BaseLogger>&`

2020-04-04 11:10 UTC, a-badin commented on log_lib/src/Logger.cpp
> +    void set_global_logger(std::unique_ptr<BaseLogger>&& other) {
Разницы с просто std::unique_ptr<BaseLogger> практически нет

2020-04-04 11:10 UTC, a-badin commented on log_lib/src/Logger.cpp
> +class Logger {
В целом не задумывалось делать этот класс невидимым из заголовков. У вас тогда нет вохможности расширить функциональность новым BaseLogger'ом не изменяя код билиотеки

2020-04-04 14:52 UTC, VIXER13 commented on log_lib/include/BaseLogger.hpp
> +    explicit BaseLogger(const Level lvl);
Всегда стараюсь стремиться к максимальной константности во всём. Не только в сигнатурах функций, но и в самом коде если это возможно.

2020-04-04 14:54 UTC, VIXER13 commented on log_lib/include/FileLogger.hpp
> +    explicit FileLogger(const std::string& path, const Level lvl);
Лучше явно указать explicit, хуже точно не будет.
С 11 стандарта в этом ключевом слове появился смысл для любого количества параметров https://habr.com/ru/post/436296/

2020-04-04 15:04 UTC, VIXER13 commented on log_lib/src/Logger.cpp
> +    Logger::get_instance().set_global_logger(std::make_unique<StdoutLogger>(lvl));
Не совсем понял идею. unique_ptr на логгер в смысле на Logger, который синглтон?

2020-04-04 15:06 UTC, VIXER13 commented on log_lib/src/Logger.cpp
> +    std::unique_ptr<BaseLogger>& get_global_logger() noexcept {
Потому что подразумевается временное пользование без владения ресурсом

2020-04-04 15:48 UTC, VIXER13 commented on log_lib/src/Logger.cpp
> +class Logger {
Я вспомнил почему я так сделал. Из-за метода get_global_logger, чтобы у пользователя не было возможности "украсть" global_logger_ при помощи std::move.

2020-04-07 11:08 UTC, a-badin commented on CMakeLists.txt
> +target_include_directories(logger PRIVATE ${LOGGER_LIB_HEADERS})
PUBLIC

2020-04-07 11:08 UTC, a-badin commented on CMakeLists.txt
> +target_include_directories(hw2 PRIVATE ${HEADERS} ${LOGGER_LIB_HEADERS})
LOGGER_LIB_HEADERS не нужен

2020-04-07 11:08 UTC, a-badin commented on log_lib/src/Logger.cpp
> +    Logger::get_instance().set_global_logger(std::make_unique<StdoutLogger>(lvl));
`return std::make_unique<StdoutLogger>(lvl)`

2020-04-07 11:08 UTC, a-badin commented on log_lib/src/Logger.cpp
> +    std::unique_ptr<BaseLogger>& get_global_logger() noexcept {
Тогда верните ref на BaseLogger или сырой указатель

2020-04-07 11:23 UTC, a-badin commented on log_lib/src/Logger.cpp
> +class Logger {
На самом деле, совсем запретить что-то в С++ практически невозможно. Ну вы можете вернуть const ref на BaseLogger, а пользователь его скастит к non-const и все равно украдет. Другой вопрос зачем ему красть логгер, если он может создать свой.
Плюс чтобы вызвать move ему нужен экземпляр BaseLogger, а это абстрактный класс

2020-04-07 11:25 UTC, a-badin requested changes
Доправляем и засчитываем.

2020-04-07 11:35 UTC, VIXER13 commented on log_lib/src/Logger.cpp
> +    Logger::get_instance().set_global_logger(std::make_unique<StdoutLogger>(lvl));
Переделал. Я просто думал, что это функции создания глобального логгера.

2020-04-07 11:35 UTC, VIXER13 commented on CMakeLists.txt
> +target_include_directories(logger PRIVATE ${LOGGER_LIB_HEADERS})
Исправил

2020-04-07 11:36 UTC, VIXER13 commented on CMakeLists.txt
> +target_include_directories(hw2 PRIVATE ${HEADERS} ${LOGGER_LIB_HEADERS})
Действительно не нужен, удалил

2020-04-07 11:38 UTC, VIXER13 commented on log_lib/src/Logger.cpp
> +    std::unique_ptr<BaseLogger>& get_global_logger() noexcept {
Я переделал, чтобы она возвращала ref на BaseLogger, но мне всё равно не нравится, что этот метод доступен пользователю. Потому что он этим ref'ом также может "украсть" global_logger_ через std::move. Но это, конечно, можно списать на неправильное пользование библиотекой

2020-04-09 07:30 UTC, a-badin requested changes

2020-04-09 07:30 UTC, a-badin commented on log_lib/src/Logger.cpp
> +    return *global_logger_.get();
Во первых или *global_logger_ или global_logger_->get();
Во вторых, а если в set_global_logger передадут пустой указатель, то тут мы упадем по segfault, у нас еще и метод noexcept

2020-04-09 08:09 UTC, merged