Hw3
VIXER13/AdvCpp-2020.1 pull request #3
Opened 2020-04-04 20:36 UTC by VIXER13

2020-04-05 16:46 UTC, smirnov-vs requested changes
нужно оформить ПР верно

2020-04-05 16:46 UTC, smirnov-vs commented on process_lib/src/descriptor.cpp
> +    }
затесалось другое дз

2020-04-05 16:46 UTC, smirnov-vs commented on tcp_test/server_test.cpp
> +}
дебаг код не удален

2020-04-05 18:21 UTC, VIXER13 commented on process_lib/src/descriptor.cpp
> +    }
Это не совсем другое дз затесалось, это я старые ошибки исправлял, которые портили текущую работу. У меня тут раньше не было проверки и не выставлялся невалидный дескриптор.

2020-04-05 18:21 UTC, VIXER13 commented on tcp_test/server_test.cpp
> +}
Удалил

2020-04-05 23:25 UTC, smirnov-vs commented on process_lib/src/descriptor.cpp
> +    }
в пулреквест лучше не отправлять, только в свою ветку, чтобы не смешивать

2020-04-05 23:33 UTC, smirnov-vs requested changes

2020-04-05 23:33 UTC, smirnov-vs commented on tcp/include/server.hpp
> +    process_lib::Descriptor fd_;
получается эта библиотека будет таскать за собой библиотеку процессов, нужно грамотно разделить исходники, если хочешь переиспользовать

2020-04-05 23:33 UTC, smirnov-vs commented on tcp/include/server.hpp
> +    Server(const char* addr, const uint16_t port, const int max_connection = 1);
const char* заменяем

2020-04-05 23:33 UTC, smirnov-vs commented on tcp/src/connection.cpp
> +    if (inet_ntop(PF_INET, &sock_info.sin_addr, addr.data(), static_cast<socklen_t>(addr.size())) == nullptr) {
addr вроде дальше никак не используется

2020-04-05 23:33 UTC, smirnov-vs commented on tcp/src/connection.cpp
> +    opened_ = other.opened_;
лучше в список инициализации

2020-04-05 23:33 UTC, smirnov-vs commented on tcp/src/connection.cpp
> +    opened_ = other.opened_;
вообще их дефолтными надо объявить, компилятор сам за тебя все сделает

2020-04-05 23:33 UTC, smirnov-vs commented on tcp/src/server.cpp
> +    auto fd = process_lib::Descriptor(::accept(fd_, reinterpret_cast<sockaddr*>(&client), &addr_size));
лучше конечный тип написать вместо auto

2020-04-05 23:33 UTC, smirnov-vs commented on tcp_test/server_test.cpp
> +        size_t len_read = connection.read(const_cast<char*>(str.data()), len);
const_cast тут не нужен

2020-04-05 23:33 UTC, smirnov-vs commented on tcp/include/connection.hpp
> +    void set_recv_timeout(const __time_t sec, const __suseconds_t usec = 0);
вроде `__` не нужны

2020-04-06 18:35 UTC, VIXER13 commented on tcp/include/connection.hpp
> +    void set_recv_timeout(const __time_t sec, const __suseconds_t usec = 0);
Действительно не нужны. Убрал.

2020-04-06 18:35 UTC, VIXER13 commented on tcp_test/server_test.cpp
> +        size_t len_read = connection.read(const_cast<char*>(str.data()), len);
Убрал

2020-04-06 18:37 UTC, VIXER13 commented on tcp/src/server.cpp
> +    auto fd = process_lib::Descriptor(::accept(fd_, reinterpret_cast<sockaddr*>(&client), &addr_size));
Слышал мнение, что в подобных контекстах, где дважды повторяется тип, лучше писать auto

2020-04-06 18:37 UTC, VIXER13 commented on tcp/src/connection.cpp
> +    opened_ = other.opened_;
Всё время забываю про эту фишку. Убрал

2020-04-06 18:38 UTC, VIXER13 commented on tcp/src/connection.cpp
> +    if (inet_ntop(PF_INET, &sock_info.sin_addr, addr.data(), static_cast<socklen_t>(addr.size())) == nullptr) {
Тут я чёт так и не понял, а откуда мне адрес брать?

2020-04-06 18:39 UTC, VIXER13 commented on tcp/include/server.hpp
> +    Server(const char* addr, const uint16_t port, const int max_connection = 1);
Заменил на const std::string&

2020-04-06 18:39 UTC, VIXER13 commented on tcp/include/server.hpp
> +    process_lib::Descriptor fd_;
Мне тоже это не нравится. Может лучше тогда классы Descriptor и Pipe в отдельную библиотеку вынести?

2020-04-06 18:43 UTC, VIXER13 commented on process_lib/src/descriptor.cpp
> +    }
Как тогда лучше поступить если я уже накосячил? Допустим я сейчас сделаю исправления в мастере, как мне их оттуда перенести в эту ветку?

2020-04-08 23:02 UTC, smirnov-vs commented on process_lib/src/descriptor.cpp
> +    }
придется переделывать ветку, в этот раз простим

2020-04-08 23:03 UTC, smirnov-vs commented on tcp/include/server.hpp
> +    process_lib::Descriptor fd_;
хорошая мысль

2020-04-08 23:04 UTC, smirnov-vs commented on tcp/src/connection.cpp
> +    if (inet_ntop(PF_INET, &sock_info.sin_addr, addr.data(), static_cast<socklen_t>(addr.size())) == nullptr) {
ну адрес ты взял, но это локальная переменная

2020-04-08 23:05 UTC, smirnov-vs commented on tcp/src/connection.cpp
> +    opened_ = other.opened_;
убрал, но дефолтными не сделал, теперь это не работает

2020-04-08 23:06 UTC, smirnov-vs commented on tcp/src/server.cpp
> +    auto fd = process_lib::Descriptor(::accept(fd_, reinterpret_cast<sockaddr*>(&client), &addr_size));
если у тебя там explicit, тогда надо `Descriptor fd{...};`

2020-04-08 23:09 UTC, smirnov-vs commented
я тебе ответил, но не заметил, что ты не запросил ревью
но думаю это ничего не нарушило

2020-04-17 16:35 UTC, closed without merging