Hw4
VIXER13/AdvCpp-2020.1 pull request #6
Opened 2020-04-11 19:53 UTC by VIXER13

2020-04-15 20:01 UTC, a-badin requested changes
Подробно обусдим в пятницу

2020-04-15 20:01 UTC, a-badin commented on examples/hw4/src/main.cpp
> +                    size_t writed = connection.write(connection.getWriteBuffer().c_str() + connection.getWrited(),
А если write_buffer еще пуст?

2020-04-15 20:01 UTC, a-badin commented on examples/hw4/src/main.cpp
> +                    connection.setWrited(connection.getWrited() + writed);
written

2020-04-15 20:01 UTC, a-badin commented on libraries/epoll_server/src/Connection.cpp
> +const uint32_t& Connection::getEvents() const noexcept {
это же 4 байта верните их по значению

2020-04-15 20:01 UTC, a-badin commented on libraries/epoll_server/src/Server.cpp
> +    opened_ = false;
Есть какой-то смысл в это флаге?

2020-04-15 20:01 UTC, a-badin commented on libraries/epoll_server/src/Connection.cpp
> +#include "string.h"
системные библиотеки в <>

2020-04-17 14:30 UTC, VIXER13 commented on libraries/epoll_server/src/Connection.cpp
> +#include "string.h"
Поправил

2020-04-17 14:31 UTC, VIXER13 commented on libraries/epoll_server/src/Server.cpp
> +    opened_ = false;
Вообще говоря он оказался не нужен, потому что у нас за открытыми дескрипторами теперь следит epoll. Убрал его из сервера и из connection

2020-04-17 14:31 UTC, VIXER13 commented on libraries/epoll_server/src/Connection.cpp
> +const uint32_t& Connection::getEvents() const noexcept {
По инерции написал, вернул по значению

2020-04-17 14:32 UTC, VIXER13 commented on examples/hw4/src/main.cpp
> +                    connection.setWrited(connection.getWrited() + writed);
Поправил

2020-04-17 14:35 UTC, VIXER13 commented on examples/hw4/src/main.cpp
> +                    size_t writed = connection.write(connection.getWriteBuffer().c_str() + connection.getWrited(),
Ну это же по идее от обработки запроса зависит. Если мы будем этот ответ куда-то дальше посылать и откуда ещё считывать, то наверное понадобятся какие-то более сложные механизмы слежения, а весь ли ответ мы получили, но здесь, для простоты, я подразумевал, что ответ генерирует непосредственно сервер и сразу же после того как он считал нужное количество байт.

2020-04-26 10:17 UTC, a-badin approved these changes

2020-04-26 10:17 UTC, a-badin commented on examples/hw4/src/main.cpp
> +    try {
Сильно, обычно 3 уровня вложенности - уже должно насторожить
У нас колбеки это std::function можно класть туда и функцию, и метод класа. 
Если вы не храните состоние лучше вынести колбек в глобальную функцию.
Если храните, можно сделать отдельный класс, с емкими методами,  и передавать в сервер объект этого класса через std::bind

2020-04-26 10:17 UTC, a-badin commented on examples/hw4/src/main.cpp
> +                        connection.setEvents(epoll_server::Connection::DISCONECT);
Вполне вариант, единственное лучше завести свой какой-то данных под Events чтобы не смешивать ваши event'ы и epoll'ные

2020-04-26 10:18 UTC, merged