Hw5
VIXER13/AdvCpp-2020.1 pull request #7
Opened 2020-04-20 15:23 UTC by VIXER13

2020-04-21 23:58 UTC, smirnov-vs requested changes

2020-04-21 23:58 UTC, smirnov-vs commented on examples/hw5/src/main.cpp
> +    shmem::ShMap<size_t, size_t> sequence_map(1024*1024*1024), parallel_map(1024*1024*1024);
неименованные константы

2020-04-21 23:58 UTC, smirnov-vs commented on libraries/shmem/src/shared_memory.cpp
> +    return {mmap, ShmemUniquePtrDeleter{size}};
думаю, можно заменить deleter лямбдой, тип данных тогда вроде будет просто std::function

2020-04-21 23:58 UTC, smirnov-vs commented on libraries/shmem/src/semaphore.cpp
> +SemaphoreLock::SemaphoreLock(Semaphore& semaphore) :
можно использовать lock_guard если методы переименовать

2020-04-21 23:58 UTC, smirnov-vs commented on libraries/shmem/include/linear_allocator.hpp
> +        ::memset(p, 0, n * sizeof(T)); // Считаем, что работаем с POD-типами, поэтому просто обнуляем их
это скорее действие метода destroy

2020-04-21 23:58 UTC, smirnov-vs commented on libraries/shmem/containers/shmap.hpp
> +    SemaphoreLock lock_left (const_cast<ShMap<Key, T, Compare>&>(left ).getSemaphore()),
почему бы не сделать метод const?

2020-04-21 23:58 UTC, smirnov-vs commented on libraries/shmem/containers/shmap.hpp
> +        return getMap().emplace_hint(hint, args...);
rvalue станут lvalue

2020-04-21 23:58 UTC, smirnov-vs commented on libraries/shmem/containers/shmap.hpp
> +        return getMap().insert(value);
скопирует

2020-04-21 23:58 UTC, smirnov-vs commented on libraries/shmem/containers/shmap.hpp
> +        map = new (map) map_type{alloc};
обычно это метод construct аллокатора

2020-04-21 23:58 UTC, smirnov-vs commented on libraries/shmem/containers/shmap.hpp
> +        allocator_type alloc(memory_, sizeof(map_type) + sizeof(Semaphore));
что если reserve_bytes передадут?

2020-04-22 09:11 UTC, VIXER13 commented on libraries/shmem/src/shared_memory.cpp
> +    return {mmap, ShmemUniquePtrDeleter{size}};
Я считаю, что это не очень хорошее решение по целому ряду критериев:
Во-первых при использовании std::function наш указатель будет очень много весить (40 байт, против 16 в моём случае).
Во-вторых, выделение класса делитера позволяет специализировать такие указатели исключительно под шареную память и их нельзя будет спутать с другими указателями у которых делитер std::function.
В-третьих, это позволяет навязать дополнительную логику не делая дополнительных обёрток (можно узнать объём буффера, на которую указывает указатель).
Ну и в-четвёртых, хоть для делитера это не столь актуальный фактор, всё же вызов std::function заметно проигрывает прямому вызову из-за косвенной адресации.

2020-04-22 09:12 UTC, VIXER13 commented on libraries/shmem/src/semaphore.cpp
> +SemaphoreLock::SemaphoreLock(Semaphore& semaphore) :
Не догадался так сделать. Удалил SemaphoreLock.

2020-04-22 09:12 UTC, VIXER13 commented on examples/hw5/src/main.cpp
> +    shmem::ShMap<size_t, size_t> sequence_map(1024*1024*1024), parallel_map(1024*1024*1024);
Именовал

2020-04-22 09:14 UTC, VIXER13 commented on libraries/shmem/include/linear_allocator.hpp
> +        ::memset(p, 0, n * sizeof(T)); // Считаем, что работаем с POD-типами, поэтому просто обнуляем их
destroy помечен как deprecated в C++17 и удалён из 20-го стандарта
https://en.cppreference.com/w/cpp/memory/allocator/destroy

2020-04-22 09:14 UTC, VIXER13 commented on libraries/shmem/containers/shmap.hpp
> +    SemaphoreLock lock_left (const_cast<ShMap<Key, T, Compare>&>(left ).getSemaphore()),
Это дружественная функция, а не метод

2020-04-22 09:14 UTC, VIXER13 commented on libraries/shmem/containers/shmap.hpp
> +        return getMap().emplace_hint(hint, args...);
Поправил

2020-04-22 09:14 UTC, VIXER13 commented on libraries/shmem/containers/shmap.hpp
> +        return getMap().insert(value);
Поправил

2020-04-22 09:19 UTC, VIXER13 commented on libraries/shmem/containers/shmap.hpp
> +        allocator_type alloc(memory_, sizeof(map_type) + sizeof(Semaphore));
Наверное это не очень хорошее решение с моей стороны, задать минимально возможный объём памяти, который требуется для создания контейнера в параметр по-умолчанию.

А вообще, если объём будет меньше минимального, то при создании аллокатора будет выкинуто исключение, а если больше, то всё будет ок.

P.S. скорее всего эта логика немного поменяется после того как я разберусь с методом construct.

2020-04-22 17:18 UTC, VIXER13 commented on libraries/shmem/containers/shmap.hpp
> +        map = new (map) map_type{alloc};
Добавил метод, только теперь из-за него конструктор ShMap какой-то костыльный получился, не знаю как правильней сделать

2020-04-26 15:04 UTC, smirnov-vs commented on libraries/shmem/include/linear_allocator.hpp
> +        ::memset(p, 0, n * sizeof(T)); // Считаем, что работаем с POD-типами, поэтому просто обнуляем их
`allocator_traits::destroy`

2020-04-26 15:05 UTC, smirnov-vs commented on libraries/shmem/containers/shmap.hpp
> +    SemaphoreLock lock_left (const_cast<ShMap<Key, T, Compare>&>(left ).getSemaphore()),
`.getSemaphore()` этот

2020-04-26 15:15 UTC, smirnov-vs reviewed
обсудим после лекции

2020-04-26 15:15 UTC, smirnov-vs commented on libraries/shmem/containers/shmap.hpp
> +        return map_->at(key);
кстати лок отпустит, а вот пользователь получит ссылку на шареную память без лока уже, будет гонка

2020-04-26 15:15 UTC, smirnov-vs commented on libraries/shmem/include/linear_allocator.hpp
> +	struct rebind {
нигде не используется?

2020-04-26 15:15 UTC, smirnov-vs commented on libraries/shmem/containers/shmap.hpp
> +        shmem::LinearAllocator<map_type> map_alloc{semaphore_alloc};
здесь думаю достаточно только аллокатора для мапы, ведь именно для нее мы его делаем, так как там сложная логика внутри
хедер памяти можно инициализировать прямо тут вручную

2020-04-26 15:24 UTC, VIXER13 commented on libraries/shmem/containers/shmap.hpp
> +    SemaphoreLock lock_left (const_cast<ShMap<Key, T, Compare>&>(left ).getSemaphore()),
Я уже заменил метод указателем на семафор и сделал его mutable, чтобы не мучиться с const_cast'ом.

2020-04-26 15:32 UTC, VIXER13 commented on libraries/shmem/containers/shmap.hpp
> +        return map_->at(key);
Это уже по идее на совести пользователя, в моей компетенции дать ему корректную ссылку при обращении, а что с ней станет через секунду я знать не могу

2020-04-26 15:32 UTC, VIXER13 commented on libraries/shmem/include/linear_allocator.hpp
> +	struct rebind {
Я просто полностью повторил все typedef'ы std::allocator. Но сейчас в чатике активно обсуждали std::allocator_traits, возможно я зря это всё сделал.

2020-04-26 15:53 UTC, smirnov-vs commented on libraries/shmem/containers/shmap.hpp
> +        return map_->at(key);
отдавай по значению

2020-04-26 15:55 UTC, smirnov-vs commented on libraries/shmem/containers/shmap.hpp
> +    std::lock_guard<Semaphore> lock_left(*left.semaphore_), lock_right(*right.semaphore_);
кстати можно заменить на scoped_lock

2020-04-26 16:16 UTC, VIXER13 commented on libraries/shmem/containers/shmap.hpp
> +        return map_->at(key);
По значению, конечно, можно, но ведь std::map так же не даёт никаких гарантий в данной ситуации и уже пользователю приходится как-то выкручиваться, чтобы избежать гонки

2020-04-26 16:34 UTC, VIXER13 commented on libraries/shmem/containers/shmap.hpp
> +        return map_->at(key);
Мне кажется здесь, в качестве безопасной альтернативы, можно просто добавить дополнительный метод и тогда все будут при своём

2020-04-26 23:14 UTC, VIXER13 commented on libraries/shmem/containers/shmap.hpp
> +    std::lock_guard<Semaphore> lock_left(*left.semaphore_), lock_right(*right.semaphore_);
Точно, иначе бы на самопроверке случился бы deadlock

2020-04-26 23:17 UTC, VIXER13 commented on libraries/shmem/containers/shmap.hpp
> +        return map_->at(key);
Мне всё-таки не очень нравится идея возвращать по значению, поэтому в качестве компромисса добавил atSafe и перегрузил operator() в качестве альтернативы operator[], которые возвращают по значению

2020-04-26 23:19 UTC, VIXER13 commented on libraries/shmem/include/linear_allocator.hpp
> +        ::memset(p, 0, n * sizeof(T)); // Считаем, что работаем с POD-типами, поэтому просто обнуляем их
Переделал функцию deallocate. Теперь она чистит буффер в том случае, когда мы удаляем из него абсолютно всё, а destroy оставил на совесть allocator_traits

2020-04-26 23:20 UTC, VIXER13 commented on libraries/shmem/containers/shmap.hpp
> +        shmem::LinearAllocator<map_type> map_alloc{semaphore_alloc};
Так и не понял как это можно адекватно переделать, поэтому оставил как есть, только метод construct использую из allocator_traits

2020-04-27 17:53 UTC, smirnov-vs approved these changes

2020-05-10 10:44 UTC, merged